#ifndef __AIUI_AUDIO_CONTROL_H__
#define __AIUI_AUDIO_CONTROL_H__
#include "asm/cpu.h"

typedef enum aiui_audio_ctrl_cmd_s {
    AIUI_AUDIO_CTRL_TTS = 0,
    AIUI_AUDIO_CTRL_PLAY,
    AIUI_AUDIO_CTRL_RESUME,
    AIUI_AUDIO_CTRL_STOP,
    AIUI_AUDIO_CTRL_NEXT,
    AIUI_AUDIO_CTRL_NEXT_SONG,
    AIUI_AUDIO_CTRL_PREV,
    AIUI_AUDIO_CTRL_PREV_SONG,
    AIUI_AUDIO_CTRL_CHECK_VIP,
    AIUI_AUDIO_SINGLE_PLAY,
    AIUI_AUDIO_ORDER_PLAY,
    AIUI_AUDIO_RANDOM_PLAY,
    AIUI_AUDIO_CTRL_PLAY_END,
    AIUI_AUDIO_CTRL_VOLUP,
    AIUI_AUDIO_CTRL_VOLDOWN,
    AIUI_AUDIO_CTRL_VOLVALUE,
    AIUI_AUDIO_CTRL_VOLMAX,
    AIUI_AUDIO_CTRL_VOLMIN,
    AIUI_AUDIO_CTRL_SET_STATE,
    AIUI_AUDIO_CTRL_REMIND_1,
    AIUI_AUDIO_CTRL_REMIND_2,
    AIUI_AUDIO_CTRL_REMIND_3,
    AIUI_AUDIO_CTRL_ALARM,
    AIUI_AUDIO_CTRL_WAKEUP,
    AIUI_AUDIO_CTRL_COLLCECT,
    AIUI_AUDIO_CTRL_DELETE,
    AIUI_AUDIO_CTRL_REPLAY,
    AIUI_AUDIO_CTRL_CHOOSE,
    AIUI_AUDIO_CTRL_MAX
} aiui_audio_ctrl_cmd_t;

int aiui_audio_ctrl_init();

void aiui_audio_control_deinit();

int aiui_audio_ctrl_cmd(aiui_audio_ctrl_cmd_t cmd, void *param);
#endif // __AIUI_AUDIO_CONTROL_H__