#ifndef __USER_MAIN_TASK_H__
#define __USER_MAIN_TASK_H__

typedef struct tag_t_UserMessage {
    int id;
    int wParam;
    int lParam;
    void *data;
    int data_len;
} t_UserMessage;

#define SYS_USERMSG_EVENT           0x0020
enum {
    MSG_IFLY_ = 800,
    IFLY_RESPONSE_TYPE_NONE,
    IFLY_RESPONSE_TYPE_LOGIN,
    IFLY_RESPONSE_TYPE_LOGOUT,
    IFLY_RESPONSE_TYPE_VAD,
    IFLY_RESPONSE_TYPE_INTERMEDIATE_TEXT,
    IFLY_RESPONSE_TYPE_ERROR,
    IFLY_RESPONSE_TYPE_TIME_STAMP,
    IFLY_RESPONSE_TYPE_ALARM_CHANGED,
    IFLY_RESPONSE_TYPE_CHANGE_VOLUME,
    IFLY_RESPONSE_TYPE_PLAY_URL,
    IFLY_RESPONSE_TYPE_CUSTOM,
    IFLY_RESPONSE_TYPE_REPLY_KEY,
    IFLY_RESPONSE_TYPE_PLAY_CONTROL,
    IFLY_RESPONSE_TYPE_BODY_IMAGE_URL,

    MSG_AUDIO_ = 900,
    MSG_AUDIO_IVW_RES_CB,
    MSG_AUDIO_RECOGNIZE_STARTED,
    MSG_AUDIO_RECOGNIZE_STOPPED,
    MSG_AUDIO_OFFLINE_COMMAND,
    MSG_AUDIO_REMIND,
    MSG_AUDIO_REMIND2,
    MSG_AUDIO_EMPTY_LIST,
    MSG_AUDIO_MUSIC_NO_AUTH,
    MSG_AUDIO_MUSIC_NO_LOGIN,
    MSG_AUDIO_FIRST_MUSIC,
    MSG_AUDIO_LAST_MUSIC,
    MSG_AUDIO_VIP_PROMPT,
    MSG_AUDIO_PAY_PROMPT,

    MSG_MAIN_TASK_ = 1000,
    MSG_MAIN_TASK_WIFI_DISCONNECTED,
    MSG_MAIN_TASK_WIFI_CONNECTED,
    MSG_MAIN_TASK_BT_DISCONNECTED,
    MSG_MAIN_TASK_BT_CONNECTED,
    MSG_MAIN_TASK_BUTTON_EVENT,
    MSG_MAIN_TASK_UPGRADE_FIRMWARE_CHECK,
    MSG_MAIN_TASK_UPGRADE_FIRMWARE,
    MSG_MAIN_TASK_POWEROFF,
    MAIN_TASK_DELEGATE_MSG_SEND,
    MAIN_TASK_DELEGATE_MSG_RECV,
    MSG_WIFI_CONFIG_BLE,
    MSG_WIFI_CONFIG_BLE_RECEIVE_SSID,
    MSG_WIFI_CONFIG_BLE_FINISH,
    MSG_MAIN_TASK_CHECKALARM,
    MSG_MAIN_TASK_TOKEN_ERROR,
    MSG_MAIN_TASK_BACKLIGHT,
    MSG_MAIN_TASK_ALARMIND,
    MSG_MAIN_TASK_VOICE_CMD,
    MSG_MAIN_TASK_SECOND_EVT,
    MSG_MAIN_TASK_SCR_ONOFF,
    MSG_MAIN_TASK_WEATHERINFOREADYIND,
    MSG_MAIN_TASK_WEATHER_INFO,
    MSG_MAIN_TASK_TEST,
    MSG_MAIN_TASK_TEST2,
    MSG_MAIN_TASK_WIFI_STA_SCAN_COMPLETED,
    MSG_MAIN_TASK_IFLY_AUTH,
    MSG_MAIN_TASK_MEDIA_END,
    MSG_MAIN_TASK_OTA_RECORD,
    MSG_MAIN_TASK_IOT_ALARM_CLOCK_COUNT_IND,
    MSG_MAIN_TASK_HTTP_ALARM_CLOCK_COUNT_IND,
    MSG_MAIN_TASK_ALARM_GET_INFO,
    MSG_MAIN_TASK_OTA_PROGRESS,
    MSG_MAIN_TASK_VOLUEM_CHANGED,
    MSG_MAIN_TASK_EMITTER_ENABLE,
    MSG_MAIN_TASK_MAX, // to be the end message id.
};

enum {
    IFLY_ERORR_CODE_NONE = 0,
    IFLY_ERROR_CODE_SDK_NO_AUTH,
    IFLY_ERROR_CODE_AIUI_NO_AUTH,
    IFLY_ERROR_CODE_XIOT_NO_AUTH,
    IFLY_ERROR_CODE_MUSIC_NO_AUTH,
    IFLY_ERROR_CODE_WIFI_NOT_CONNECTED,
    IFLY_ERROR_CODE_SERVER_NOT_CONNECTED,
    IFLY_ERROR_CODE_SEND_VOCIE_FAIL,
    IFLY_ERROR_CODE_IN_NET_CONFIG_STATE,
};

int main_task_post_message(int id, int wParam, int lParam, void *data, int data_len);
int main_task_user_message_proc(t_UserMessage *pp_UserMessage);
int main_task_callbacks_do(int id, int wParam, int lParam, void *data, int data_len);

#endif /* __USER_MAIN_TASK_H__ */
